analyze_supplementation:
  description: >
    Analise a tabela de suplementação do Notion e verifique:
    - Se há interações negativas entre suplementos e medicamentos.
    - Se a ingestão está alinhada com recomendações científicas.
    - Se há sugestões para melhorar a rotina de suplementação.

  expected_output: >
    Um relatório estruturado com:
    - Lista de suplementos e medicamentos analisados.
    - Possíveis interações negativas.
    - Sugestões de ajustes na rotina de consumo.
    - Reforço sobre quais suplementos são essenciais.

  tools: 
    - fetch_notion_supplements
  agent: analysis_agent


research_best_supplements:
  description: >
    Pesquise por suplementos de melhor qualidade e custo-benefício, considerando:
    - Opções que combinem múltiplas vitaminas em um só produto.
    - Redução na quantidade de cápsulas ingeridas.
    - Comparação de preços e marcas confiáveis.
  
  expected_output: >
    Uma lista estruturada com:
    - Suplementos recomendados com base em qualidade e custo.
    - Opções que reduzem a quantidade de cápsulas.
    - Links para compra dos produtos recomendados.

  tools: 
    - search_pubmed
    - search_best_supplements
  agent: research_agent


send_supplementation_report:
  description: >
    Envie um e-mail com um relatório estruturado contendo:
    - A análise do `Analysis Agent` sobre a suplementação.
    - A pesquisa do `Research Agent` sobre melhores suplementos e preços.
    - Sugestões de ajustes na rotina de ingestão.
    - Opções de compra e links para os suplementos recomendados.

  expected_output: >
    Um e-mail bem formatado, contendo:
    - A análise detalhada da combinação de suplementos.
    - Recomendações de suplementos mais eficientes e econômicos.
    - Links confiáveis para compra dos produtos.

  tools: 
    - send_health_report_tool
  agent: email_agent
