name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
- type: textarea
  id: issue_description
  attributes:
    label: Describe the Feature
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: issue_importance
  attributes:
    label: Why is this feature important?
    description: Explain why this feature is important and how it will benefit the project.
  validations:
    required: true
- type: textarea
  id: additional_context
  attributes:
    label: Additional Context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
